### ISSUE TITLE
有新版了，2016.3.4，麻烦作者更新一下

### ISSUE THREAD

**Issue by zed76r** [Xuanwo/datagrip-chocolatey-package#5]
https://download.jetbrains.com/datagrip/datagrip-2016.3.4.exe

多谢啦，辛苦。

**Comment by Xuanwo** [comment]
OK，我周末抽空加一下，如果着急的话可以看主页的Readme提交一个PR

**Comment by Xuanwo** [comment]
Build ref: https://ci.appveyor.com/project/Xuanwo/datagrip-chocolatey-package/build/2016.3.4.32
